NATURAL LANGUAGE **PROCESSING**

FIRST SECTION **TOKENIZATION**





In [ ]:
import tensorflow as tf    #importing tensorflow library
from tensorflow import keras #importing keras
from tensorflow.keras.preprocessing.text import Tokenizer #importing tokenizer api

In [ ]:
sentences=['I love my Dog', 'I love my Cat','You love my dog!']


In [ ]:
tokenizer=Tokenizer(num_words=100,oov_token="<OOV>")  #num of words to keep
tokenizer.fit_on_texts(sentences) #fits on the sentences
word_index=tokenizer.word_index  #Finding word index
print(word_index)  

{'<OOV>': 1, 'love': 2, 'my': 3, 'i': 4, 'dog': 5, 'cat': 6, 'you': 7}


In [ ]:
sequences=tokenizer.texts_to_sequences(sentences)
print(sequences)

[[4, 2, 3, 5], [4, 2, 3, 6], [7, 2, 3, 5]]


In [ ]:
test_data=["I really love my dog", 'My dog loves my mannnate']
tokenizer=Tokenizer(num_words=100,oov_token="<OOV>")  #num of words to keep
tokenizer.fit_on_texts(sentences) #fits on the sentences
# word_index=tokenizer.word_index  #Finding word index
# print(word_index) 
test_sequences=tokenizer.texts_to_sequences(test_data)
print(test_sequences)

[[4, 1, 2, 3, 5], [3, 5, 1, 3, 1]]


In [ ]:
#Pad sequencing

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
new_sequences=['I love my Sister', 'I love my neice', 'I love both my neice and my sister']
tokenier=Tokenizer(num_words=100,oov_token="<OOV>")
tokenizer.fit_on_texts(new_sequences)
new_sequences_text=tokenizer.texts_to_sequences(new_sequences)
print(new_sequences_text)
padded=pad_sequences(new_sequences_text,padding='post')
print(padded)

[[4, 3, 2, 6], [4, 3, 2, 7], [4, 3, 10, 2, 7, 11, 2, 6]]
[[ 4  3  2  6  0  0  0  0]
 [ 4  3  2  7  0  0  0  0]
 [ 4  3 10  2  7 11  2  6]]


In [ ]:
#TRAINING
# ON NEWS HEADLINE

import json

with open('/content/drive/MyDrive/sar_xy.json','r') as f:
  datastore=json.load(f)
# print(datastore)
sentences=[]
labels=[]
urls=[]

for item in datastore:
    sentences.append(item['headline'])
    labels.append(item['is_sarcastic'])
    urls.append(item['article_link'])
  

In [ ]:
#create tokens

# tokenier=Tokenizer(num_words=100,oov_token="<OOV>")
# tokenizer.fit_on_texts(sentences)
# word_index=tokenizer.word_index  #Finding word index
# print(word_index)  
# new_sequences_text=tokenizer.texts_to_sequences(sentences)
# print(new_sequences_text)
# padded=pad_sequences(new_sequences_text,padding='post')
# print(padded)
# print(padded.shape)

{'<OOV>': 1, 'to': 2, 'of': 3, 'the': 4, 'in': 5, 'for': 6, 'a': 7, 'on': 8, 'and': 9, 'with': 10, 'is': 11, 'new': 12, 'trump': 13, 'man': 14, 'from': 15, 'at': 16, 'about': 17, 'you': 18, 'this': 19, 'by': 20, 'after': 21, 'up': 22, 'out': 23, 'be': 24, 'how': 25, 'as': 26, 'it': 27, 'that': 28, 'not': 29, 'are': 30, 'your': 31, 'his': 32, 'what': 33, 'he': 34, 'all': 35, 'just': 36, 'who': 37, 'has': 38, 'will': 39, 'more': 40, 'one': 41, 'into': 42, 'report': 43, 'year': 44, 'why': 45, 'have': 46, 'area': 47, 'over': 48, 'donald': 49, 'u': 50, 'day': 51, 'says': 52, 's': 53, 'can': 54, 'first': 55, 'woman': 56, 'time': 57, 'like': 58, 'her': 59, "trump's": 60, 'old': 61, 'no': 62, 'get': 63, 'off': 64, 'an': 65, 'life': 66, 'people': 67, 'obama': 68, 'now': 69, 'house': 70, 'still': 71, "'": 72, 'women': 73, 'make': 74, 'was': 75, 'than': 76, 'my': 77, 'white': 78, 'back': 79, 'i': 80, 'clinton': 81, 'down': 82, 'if': 83, '5': 84, 'when': 85, 'world': 86, 'could': 87, 'we': 88, 'th

In [ ]:
vocab_size = 100000
embedding_dim = 16
max_length = 100
trunc_type='post'
padding_type='post'
oov_tok = "<OOV>"
training_size = 20000
training_sentences=sentences[:20000]
test_sentences=sentences[20000:]
training_labels=labels[:20000]
test_labels=labels[20000:]



In [ ]:
tokenizer=Tokenizer(num_words=100000,oov_token="<OOV>")
tokenizer.fit_on_texts(training_sentences)
word_index=tokenizer.word_index

In [ ]:
training_sentences_sequences=tokenizer.texts_to_sequences(training_sentences)
training_sentences_padded=pad_sequences(training_sentences_sequences,padding='post',truncating=trunc_type)
# training_labels_sequences=tokenizer.texts_to_sequences(training_labels)
# training_labels_padded=pad_sequences(training_labels_sequences,padding='post')


In [ ]:
test_sentences_sequences=tokenizer.texts_to_sequences(test_sentences)
test_sentences_padded=pad_sequences(test_sentences_sequences,padding='post',truncating=trunc_type)
# test_labels_sequences=tokenizer.texts_to_sequences(test_labels)
# test_labels_padded=pad_sequences(test_sequences_labels_sequences,padding='post')

In [ ]:
import numpy as np
training_padded = np.array(training_sentences_padded)
training_labels = np.array(training_labels)
testing_padded = np.array(test_sentences_padded)
testing_labels = np.array(test_labels)

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length=max_length),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(24, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
num_epochs = 30
history = model.fit(training_padded, training_labels, epochs=num_epochs, validation_data=(testing_padded, testing_labels), verbose=2)

Epoch 1/30
625/625 - 11s - loss: 0.3137 - accuracy: 0.8783 - val_loss: 0.3425 - val_accuracy: 0.8571
Epoch 2/30
625/625 - 11s - loss: 0.2109 - accuracy: 0.9223 - val_loss: 0.3415 - val_accuracy: 0.8588
Epoch 3/30
625/625 - 11s - loss: 0.1481 - accuracy: 0.9480 - val_loss: 0.3642 - val_accuracy: 0.8556
Epoch 4/30
625/625 - 11s - loss: 0.1049 - accuracy: 0.9651 - val_loss: 0.3915 - val_accuracy: 0.8553
Epoch 5/30
625/625 - 11s - loss: 0.0737 - accuracy: 0.9773 - val_loss: 0.4329 - val_accuracy: 0.8508
Epoch 6/30
625/625 - 11s - loss: 0.0506 - accuracy: 0.9861 - val_loss: 0.5036 - val_accuracy: 0.8356
Epoch 7/30
625/625 - 11s - loss: 0.0368 - accuracy: 0.9916 - val_loss: 0.5378 - val_accuracy: 0.8419
Epoch 8/30
625/625 - 11s - loss: 0.0248 - accuracy: 0.9951 - val_loss: 0.6181 - val_accuracy: 0.8386
Epoch 9/30
625/625 - 11s - loss: 0.0167 - accuracy: 0.9973 - val_loss: 0.6660 - val_accuracy: 0.8344
Epoch 10/30
625/625 - 11s - loss: 0.0120 - accuracy: 0.9977 - val_loss: 0.7537 - val_accura

In [ ]:
sentence = ["granny starting to fear spiders in the garden might be real", "I’m not saying I hate you, what I’m saying is that you are literally the Monday of my life","Find your patience before I lose mine."]
sequences = tokenizer.texts_to_sequences(sentence)
padded = pad_sequences(sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)
print(model.predict(padded))

[[8.1777954e-01]
 [4.5022458e-10]
 [2.0813942e-04]]


In [ ]:
!pip install PyPDF2
import PyPDF2 
    
# creating a pdf file object 
pdfFileObj = open('/content/drive/MyDrive/Resume.pdf', 'rb') 
    
# creating a pdf reader object 
pdfReader = PyPDF2.PdfFileReader(pdfFileObj) 
    
# printing number of pages in pdf file 
print(pdfReader.numPages) 
    
# creating a page object 
pageObj = pdfReader.getPage(0) 
    
# extracting text from page 
print(pageObj.extractText()) 
    
# closing the pdf file object 
pdfFileObj.close() 

     |████████████████████████████████| 81kB 3.5MB/s 
  Created wheel for PyPDF2: filename=PyPDF2-1.26.0-cp37-none-any.whl size=61102 sha256=d1210ba6155999adfcbe596c7898ddca1e0cc97a95066384779d37bc52e1011e
  Stored in directory: /root/.cache/pip/wheels/53/84/19/35bc977c8bf5f0c23a8a011aa958acd4da4bbd7a229315c1b7
Successfully built PyPDF2
3



In [ ]:
k=0
!pip install gensim
!pip install yake
from gensim.summarization import keywords
import pdfplumber
import PyPDF2 
pdfFileObj = open('/content/drive/MyDrive/Resume.pdf', 'rb') 
pdfReader = PyPDF2.PdfFileReader(pdfFileObj) 
print(pdfReader.numPages) 
for i in range(0,pdfReader.numPages):
  with pdfplumber.open(r'/content/drive/MyDrive/Resume.pdf') as pdf:
    first_page = pdf.pages[i]
    
    # print(keywords(first_page.extract_text()))
    # print(first_page.extract_text())
    import yake
    kw_extractor = yake.KeywordExtractor()
    # text = """spaCy is an open-source software library for advanced natural language processing, written in the programming languages Python and Cython. The library is published under the MIT license and its main developers are Matthew Honnibal and Ines Montani, the founders of the software company Explosion."""
    language = "en"
    max_ngram_size = 3
    deduplication_threshold = 0.9
    numOfKeywords = 10000
    custom_kw_extractor = yake.KeywordExtractor(lan=language, n=max_ngram_size, dedupLim=deduplication_threshold, top=numOfKeywords, features=None)
    keywords = custom_kw_extractor.extract_keywords(first_page.extract_text())
    for kw in keywords:
      print(kw)
    




3
('BHUSHAN AVINASH PANDE', 0.0003640174148602639)
('BHUSHAN AVINASH', 0.005124667772561823)
('AVINASH PANDE', 0.005124667772561823)
('Deep learning', 0.014182958498557403)
('natural language processing', 0.014440465650516729)
('learning', 0.02066148775809439)
('machine learning', 0.022837199894608702)
('language processing', 0.02596525782050164)
('machine', 0.027774349280486773)
('natural language', 0.029082238202543884)
('skills', 0.029753283424346567)
('Key Skills', 0.030180320924023347)
('processing', 0.03529999085583114)
('Deep', 0.0410996318853314)
('Learning Deep Learning', 0.04137458906946881)
('Artificial Neural Networks', 0.04253414147278422)
('Artificial Neural', 0.042548011620397105)
('Computer Vision', 0.04595271960591709)
('KEY', 0.050076975498025596)
('Learning Machine Learning', 0.050633973174892856)
('Deep Learning Machine', 0.05435430824661325)
('Machine Learning Deep', 0.05435430824661326)
('Augean Artificial Neural', 0.055170189964148623)
('Neural Networks', 0.05566

language
languages
software
company
